language: c++

matrix:
    include:
#        - os: osx
#          compiler: clang
#          osx_image: xcode8.3
        - os: linux
          compiler: gcc
          dist: trusty
#          sudo: required
          sudo: false
          group: edge

# to use numpy and scipy installed via apt-get
#virtualenv:
#  system_site_packages: true

script:
  - ./travis.sh

notifications:
  email:
    recipients:
      - fons.rademakers@cern.ch   # - ship-software@cern.ch
    on_success: always
    on_failure: always
